trigger:
 branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub-registry'
    repository: 'jksoam777/jkapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'service-jk'
    azureResourceGroup: 'jksoam'
    kubernetesCluster: 'k8scluster'
    manifests: '$(System.DefaultWorkingDirectory)/Manifests/*.yaml'


