apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AddTask.serviceName }}
spec:
  selector:
    app: {{ .Values.AddTask.podLables }}
  ports:
    - protocol: TCP
      port: {{ .Values.AddTask.servicePort }}
      targetPort: {{ .Values.AddTask.containerPort }}
  type: {{ .Values.AddTask.serviceType }}
